# Generated by Django 5.0 on 2024-02-16 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, choices=[('TOOLS', 'Tools'), ('MASTS', 'Masts'), ('BATTERIES', 'Batteries'), ('ACCESSORIES', 'Accessories'), ('CABLES', 'Cables'), ('ANTENNAS', 'Antennas'), ('NUTS_AND_BOLTS', 'Nuts and Bolts'), ('CONNECTORS_PINS_BUS_BARS', 'Connectors, Pins, and Bus Bars'), ('SENSORS', 'Sensors'), ('BOARDS_AND_ELECTRONICS', 'Boards and Electronics'), ('SUPPORTS', 'Supports'), ('OTHERS', 'Others')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Material Registration',
                'verbose_name_plural': 'Material Registrations',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('responsible', models.CharField(max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(null=True, verbose_name='Is active?')),
                ('activation_date', models.DateTimeField(null=True, verbose_name='Storage Unit Activation Date')),
                ('closure_date', models.DateTimeField(blank=True, null=True, verbose_name='Storage Unit Closure Date')),
            ],
            options={
                'verbose_name': 'Storage Unit',
                'verbose_name_plural': 'Storage Units',
            },
        ),
        migrations.CreateModel(
            name='PackageItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_english.material', verbose_name='Material')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_english.package', verbose_name='Package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='materials',
            field=models.ManyToManyField(through='inventory_english.PackageItems', to='inventory_english.material'),
        ),
        migrations.CreateModel(
            name='MaterialQuantityPerUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_english.material')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_english.storageunit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Materials in Stock',
            },
        ),
        migrations.CreateModel(
            name='MaterialExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_date', models.DateTimeField(auto_now_add=True)),
                ('destination', models.CharField(max_length=100, null=True)),
                ('service', models.CharField(choices=[('Installation', 'Installation'), ('Preventive Maintenance', 'Preventive Maintenance'), ('Corrective Maintenance', 'Corrective Maintenance')], max_length=100)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_english.package')),
                ('debit_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_english.storageunit')),
            ],
            options={
                'verbose_name': 'External - Material Exit',
                'verbose_name_plural': 'External - Material Exits',
            },
        ),
        migrations.CreateModel(
            name='MaterialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(max_length=100, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_english.material')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_english.storageunit')),
            ],
            options={
                'verbose_name': 'External - Material Entry',
                'verbose_name_plural': 'External - Material Entries',
            },
        ),
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of departure from the sending unit')),
                ('entry_date', models.DateTimeField(blank=True, null=True, verbose_name='Date of entry at the destination unit')),
                ('delivered', models.BooleanField(null=True, verbose_name='Was it delivered to the destination unit?')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_english.package')),
                ('credit_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_transfer', to='inventory_english.storageunit')),
                ('debit_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_transfer', to='inventory_english.storageunit')),
            ],
            options={
                'verbose_name': 'Internal Material Transfer',
                'verbose_name_plural': 'Internal Material Transfers',
            },
        ),
    ]
