# Generated by Django 5.0 on 2024-02-16 20:52

import inventory_english.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_english', '0002_internaltransfer_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialquantityperunit',
            name='minimum',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='materialquantityperunit',
            name='stock_level',
            field=models.CharField(choices=[('low', 'LOW'), ('normal', 'NORMAL'), ('critical', 'CRITICAL')], default=inventory_english.models.StockLevel['NORMAL'], max_length=20),
        ),
    ]
