# Generated by Django 5.0 on 2024-02-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_english', '0004_alter_materialquantityperunit_stock_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialquantityperunit',
            name='stock_level',
            field=models.CharField(choices=[('normal', 'NORMAL'), ('critical', 'CRITICAL')], max_length=20),
        ),
    ]
