# Generated by Django 5.0 on 2023-12-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_alteracao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_unitario',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('produtos_expert', models.ManyToManyField(related_name='produtos_expert', to='estoque.produto')),
                ('produtos_standard', models.ManyToManyField(related_name='produtos_standard', to='estoque.produto')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
