# Generated by Django 5.0 on 2023-12-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_saidamaterial_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidamaterial',
            name='destino',
            field=models.CharField(default='', max_length=100),
        ),
    ]
