# Generated by Django 5.0 on 2023-12-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_saidamaterial_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidamaterial',
            name='destino',
            field=models.CharField(max_length=100),
        ),
    ]
