# Generated by Django 5.0 on 2023-12-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_rename_materiais_material'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Material',
            new_name='Componetes',
        ),
    ]
