# Generated by Django 5.0 on 2023-12-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_rename_material_componetes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Componetes',
            new_name='Componente',
        ),
    ]
