# Generated by Django 5.0 on 2023-12-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_rename_componetes_componente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componente',
            options={'verbose_name': 'Material em estoque', 'verbose_name_plural': 'Materiais em estoque'},
        ),
        migrations.AlterModelOptions(
            name='saidamaterial',
            options={'verbose_name': 'Registro de saída de Material', 'verbose_name_plural': 'Registros de saídas de Materiais'},
        ),
    ]
