# Generated by Django 5.0 on 2023-12-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_alter_componente_options_alter_saidamaterial_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Componente',
            new_name='Materiais',
        ),
    ]
