# Generated by Django 5.0 on 2023-12-23 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_categoria_materiais_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.materiais')),
            ],
            options={
                'verbose_name': 'Registro de entrada de Material',
                'verbose_name_plural': 'Registros de entradas de Materiais',
            },
        ),
    ]
