# Generated by Django 5.0 on 2024-01-22 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0019_alter_saidamaterial_tipo_de_servico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='saidamaterial',
            name='tipo_de_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.tipodeservico'),
        ),
        migrations.DeleteModel(
            name='TipoDeServiço',
        ),
    ]
