# Generated by Django 5.0 on 2024-01-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0020_tipodeservico_alter_saidamaterial_tipo_de_servico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saidamaterial',
            name='tipo_de_servico',
        ),
        migrations.DeleteModel(
            name='TipoDeServico',
        ),
    ]
