# Generated by Django 5.0 on 2024-01-22 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0022_tipodeservico_saidamaterial_tipo_de_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saidamaterial',
            name='tipo_de_servico',
        ),
        migrations.DeleteModel(
            name='TipoDeServico',
        ),
    ]
