# Generated by Django 5.0 on 2024-01-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0024_tipodeservico_saidamaterial_tipo_de_servico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoDeServico',
            new_name='Servico',
        ),
    ]
