# Generated by Django 5.0 on 2024-01-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0025_rename_tipodeservico_servico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='tipo',
            new_name='serv',
        ),
    ]
