# Generated by Django 5.0 on 2024-01-22 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0026_rename_tipo_servico_serv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'Serviço a ser realizado'},
        ),
        migrations.RemoveField(
            model_name='saidamaterial',
            name='tipo_de_servico',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='serv',
        ),
        migrations.AddField(
            model_name='saidamaterial',
            name='servico',
            field=models.ForeignKey(blank=True,  on_delete=django.db.models.deletion.CASCADE, to='estoque.servico'),
        ),
        migrations.AddField(
            model_name='servico',
            name='nome',
            field=models.CharField(default='valor', max_length=50),
            preserve_default=False,
        ),
    ]
