# Generated by Django 5.0 on 2024-01-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0027_alter_servico_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saidamaterial',
            name='servico',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
