# Generated by Django 5.0 on 2024-01-22 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0028_remove_saidamaterial_servico_delete_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Serviço a ser realizado',
            },
        ),
        migrations.AddField(
            model_name='saidamaterial',
            name='servico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.servico'),
            preserve_default=False,
        ),
    ]
