# Generated by Django 5.0 on 2024-01-22 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0029_servico_saidamaterial_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidamaterial',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.servico'),
        ),
    ]
