# Generated by Django 5.0 on 2024-01-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0030_alter_saidamaterial_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='nome',
        ),
        migrations.AddField(
            model_name='servico',
            name='tipo',
            field=models.CharField(choices=[('Instalacao', 'Instalação'), ('ManutencaoPreventiva', 'Manutenção Preventiva'), ('ManutencaoCorretiva', 'Manutenção Corretiva')], default='NONE', max_length=100),
            preserve_default=False,
        ),
    ]
