# Generated by Django 5.0 on 2024-01-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0031_remove_servico_nome_servico_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidamaterial',
            name='servico',
            field=models.CharField(choices=[('Instalação', 'Instalação'), ('Manutenção Preventiva', 'Manutenção Preventiva'), ('Manutenção Corretiva', 'Manutenção Corretiva')], max_length=100),
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria do material', 'verbose_name_plural': 'Categoria dos materiais'},
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
