# Generated by Django 5.0 on 2024-01-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0033_alter_categoria_options_materiais_em_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradamaterial',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
