# Generated by Django 5.0 on 2024-01-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0035_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeArmazenamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Unidade de Armazenamento',
                'verbose_name_plural': 'Unidades de Armazenamento',
            },
        ),
        migrations.AddField(
            model_name='materiais',
            name='unidades_armazenamento',
            field=models.ManyToManyField(blank=True, to='estoque.unidadearmazenamento'),
        ),
    ]
