# Generated by Django 5.0 on 2024-01-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0036_unidadearmazenamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiais',
            name='unidades_armazenamento',
        ),
        migrations.DeleteModel(
            name='UnidadeArmazenamento',
        ),
    ]
