# Generated by Django 5.0 on 2024-02-02 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0039_delete_categoria_alter_materiais_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='entradamaterial',
            name='responsavel',
            field=models.ForeignKey(blank=True,null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.responsavel'),
        ),
        migrations.AddField(
            model_name='saidamaterial',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.responsavel'),
        ),
    ]
