# Generated by Django 5.0 on 2024-02-02 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0040_responsavel_entradamaterial_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamaterial',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.responsavel'),
        ),
        migrations.AlterField(
            model_name='saidamaterial',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.responsavel'),
        ),
    ]
