# Generated by Django 5.0 on 2024-02-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0041_alter_entradamaterial_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='data_ativacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
