# Generated by Django 5.0 on 2024-02-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0042_responsavel_data_ativacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='is_ativo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='data_ativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de ativação do usuário'),
        ),
    ]
