# Generated by Django 5.0 on 2024-02-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0044_remove_responsavel_is_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='is_ativo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
