# Generated by Django 5.0 on 2024-02-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0045_responsavel_is_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='is_ativo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Está ativo?'),
        ),
    ]
