# Generated by Django 5.0 on 2024-02-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadearm',
            name='responsavel',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='unidadearm',
            name='data_ativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de ativação da Unidade de Armazenamento'),
        ),
        migrations.AddField(
            model_name='unidadearm',
            name='is_ativo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Está ativa?'),
        ),
        migrations.DeleteModel(
            name='Responsavel',
        ),
    ]
