# Generated by Django 5.0 on 2024-02-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantidadematerialporunidade',
            name='quantidade_em_estoque',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
