# Generated by Django 5.0 on 2024-02-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_unidadearm_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadearm',
            name='data_encerramento',
            field=models.DateTimeField(null=True, verbose_name='Data de encerramneto da Unidade de Armazenamento'),
        ),
        migrations.AlterField(
            model_name='unidadearm',
            name='data_ativacao',
            field=models.DateTimeField(null=True, verbose_name='Data de ativação da Unidade de Armazenamento'),
        ),
        migrations.AlterField(
            model_name='unidadearm',
            name='is_ativo',
            field=models.BooleanField(null=True, verbose_name='Está ativa?'),
        ),
        migrations.AlterField(
            model_name='unidadearm',
            name='nome',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadearm',
            name='responsavel',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
