# Generated by Django 5.0 on 2024-02-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradamaterial',
            name='is_externo',
            field=models.BooleanField(null=True, verbose_name='O remetente e externo?'),
        ),
        migrations.AlterField(
            model_name='unidadearm',
            name='data_encerramento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de encerramento da Unidade de Armazenamento'),
        ),
    ]
