# Generated by Django 5.0 on 2024-02-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_unidadearm_data_encerramento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadearm',
            name='data_encerramento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de encerramneto da Unidade de Armazenamento'),
        ),
    ]
