# Generated by Django 5.0 on 2024-02-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_entradamaterial_is_externo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saidamaterial',
            options={'verbose_name': 'Saída de Materiail (Externo)', 'verbose_name_plural': 'Saídas de Materiais (Externo)'},
        ),
    ]
