# Generated by Django 5.0 on 2024-02-02 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_unidadearm_data_encerramento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiais',
            name='quantidade_em_estoque',
        ),
        migrations.AddField(
            model_name='materiais',
            name='quantidade_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unidadearm',
            name='data_encerramento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de encerramento da Unidade de Armazenamento'),
        ),
        migrations.CreateModel(
            name='QuantidadeMaterialUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.materiais')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unidadearm')),
            ],
            options={
                'unique_together': {('unidade', 'material')},
            },
        ),
        migrations.AddField(
            model_name='unidadearm',
            name='materiais',
            field=models.ManyToManyField(through='inventory.QuantidadeMaterialUnidade', to='inventory.materiais'),
        ),
    ]
