# Generated by Django 5.0 on 2024-02-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_saidamaterial_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saidamaterial',
            options={'verbose_name': 'Registro de  Saída de Material (Externo)', 'verbose_name_plural': 'Registro de  Saídas de Materiais (Externo)'},
        ),
        migrations.RemoveField(
            model_name='entradamaterial',
            name='is_externo',
        ),
    ]
