# Generated by Django 5.0 on 2024-02-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_materiais_quantidade_em_estoque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantidadematerialunidade',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
