# Generated by Django 5.0 on 2024-02-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_saidamaterial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradamaterial',
            options={'verbose_name': 'Registro de Entrada de Material  (Externo)', 'verbose_name_plural': 'Registros de Entradas de Materiais  (Externo)'},
        ),
    ]
