# Generated by Django 5.0 on 2024-02-14 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_entradamaterial_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(auto_now_add=True, verbose_name='Data de saida da unidade remetente')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada na unidade de destino')),
                ('entregue', models.BooleanField(null=True, verbose_name='Foi entregue a unidade de destino?')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pacote')),
                ('unidade_credito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_credito', to='inventory.unidadearm')),
                ('unidade_debito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_debito', to='inventory.unidadearm')),
            ],
            options={
                'verbose_name': 'Transferência interna de Material',
                'verbose_name_plural': 'Transferências internas de Materiais',
            },
        ),
    ]
