# Generated by Django 5.0 on 2024-02-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_transferenciainterna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciainterna',
            name='data_entrada',
            field=models.DateTimeField(blank=True, verbose_name='Data de entrada na unidade de destino'),
        ),
    ]
