# Generated by Django 5.0 on 2024-02-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_transferenciainterna_data_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciainterna',
            name='data_entrada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de entrada na unidade de destino'),
        ),
    ]
