# Generated by Django 5.0 on 2024-02-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_transferenciainterna_data_entrada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradamaterial',
            options={'verbose_name': 'Externo - Entrada de Material', 'verbose_name_plural': 'Externo - Entradas de Materiais'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Cadastro de Material', 'verbose_name_plural': 'Cadastros de Materiais'},
        ),
        migrations.AlterModelOptions(
            name='quantidadematerialporunidade',
            options={'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoque'},
        ),
        migrations.AlterModelOptions(
            name='saidamaterial',
            options={'verbose_name': 'Externo - Saída de Material', 'verbose_name_plural': 'Externo - Saídas de Materiais'},
        ),
    ]
