# Generated by Django 5.0 on 2024-02-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_entradamaterial_options_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Cadastro de Material', 'verbose_name_plural': 'Cadastro de Materiais'},
        ),
    ]
